import type { DefaultProps } from '@sivir-ui/svelte/utils';
import type { Snippet } from 'svelte';
import type { HTMLAttributes, HTMLButtonAttributes } from 'svelte/elements';
import Root from './approval-request.svelte';
import Cancel from './approval-request-cancel.svelte';
import Confirm from './approval-request-confirm.svelte';
import Content from './approval-request-content.svelte';
import Description from './approval-request-description.svelte';
import Details from './approval-request-details.svelte';
import ErrorComponent from './approval-request-error.svelte';
import Footer from './approval-request-footer.svelte';
import Header from './approval-request-header.svelte';
import Icon from './approval-request-icon.svelte';
import Risk from './approval-request-risk.svelte';
import Status from './approval-request-status.svelte';
import Title from './approval-request-title.svelte';
export type ApprovalRisk = 'low' | 'medium' | 'high';
export type ApprovalRequestActionName = 'cancel' | 'confirm';
export type ApprovalRequestRootProps = {
    /** Controls modal visibility. Successful actions close it automatically. */
    open?: boolean;
    risk?: ApprovalRisk;
    pending?: ApprovalRequestActionName | null;
    error?: string | null;
    children?: Snippet;
};
export type ApprovalRequestContentProps = DefaultProps & Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'role'>;
export type ApprovalRequestHeaderProps = DefaultProps & Omit<HTMLAttributes<HTMLDivElement>, 'children'>;
export type ApprovalRequestStatusProps = ApprovalRequestHeaderProps;
export type ApprovalRequestIconProps = ApprovalRequestHeaderProps;
export type ApprovalRequestRiskProps = ApprovalRequestHeaderProps;
export type ApprovalRequestTitleProps = DefaultProps;
export type ApprovalRequestDescriptionProps = DefaultProps;
export type ApprovalRequestDetailsProps = ApprovalRequestHeaderProps;
export type ApprovalRequestFooterProps = ApprovalRequestHeaderProps;
export type ApprovalRequestActionProps = {
    onclick?: (event: MouseEvent) => unknown | Promise<unknown>;
    pendingLabel?: string;
    failureMessage?: string;
    children?: Snippet;
} & DefaultProps & Omit<HTMLButtonAttributes, 'children' | 'onclick' | 'status' | 'loading' | 'loadingLabel'>;
export { Cancel, Confirm, Content, Description, Details, ErrorComponent as Error, Footer, Header, Icon, Risk, Root, Status, Title };
