import Root from './approval-request.svelte';
import Cancel from './approval-request-cancel.svelte';
import Confirm from './approval-request-confirm.svelte';
import Content from './approval-request-content.svelte';
import Description from './approval-request-description.svelte';
import Details from './approval-request-details.svelte';
import ErrorComponent from './approval-request-error.svelte';
import Footer from './approval-request-footer.svelte';
import Header from './approval-request-header.svelte';
import Icon from './approval-request-icon.svelte';
import Risk from './approval-request-risk.svelte';
import Status from './approval-request-status.svelte';
import Title from './approval-request-title.svelte';
export { Cancel, Confirm, Content, Description, Details, ErrorComponent as Error, Footer, Header, Icon, Risk, Root, Status, Title };
