import type { ThemeDraft } from '@sivir/ui/themes/presets';

export const preset: ThemeDraft = {
	slug: 'default',
	name: 'Default',
	description: 'A custom theme published from the Sivir UI Theme Studio.',
	publisher: 'Sivir UI',
	fontSans: '"IBM Plex Sans", sans-serif',
	fontMono: '"SF Mono", monospace',
	fontHeader: '"IBM Plex Sans", sans-serif',
	radiusBase: '0.45rem',
	radiusSm: '0.21rem',
	radiusMd: '0.45rem',
	radiusLg: '0.55rem',
	radiusXl: '0.67rem',
	fancyShadows: true,
	spacing: {
		buttonPaddingX: 13,
		badgePaddingX: 10,
		badgePaddingY: 4,
		cardPadding: 23,
		panelPadding: 10,
		fieldPaddingX: 12,
		menuItemPaddingX: 6,
		buttonHeight: 36,
		buttonHeightSm: 32,
		buttonHeightLg: 40,
		fieldHeight: 36,
		menuItemHeight: 34,
		switchTrackWidth: 40,
		switchThumbSize: 17,
		iconButtonSize: 32,
		menuPadding: 3,
		menuLabelPaddingX: 8,
		menuLabelPaddingY: 4,
		togglePaddingSm: 8,
		togglePaddingMd: 10,
		togglePaddingLg: 14,
		tabsTriggerPaddingX: 14,
		tabsTriggerPaddingY: 6,
		tabsListPadding: 3,
		toastPaddingX: 16,
		toastPaddingY: 16,
		colorPickerPadding: 10,
		sheetHeaderPaddingBottom: 24,
		modalPadding: 16,
		modalTitleDescriptionGap: 6,
		modalSectionGap: 16,
		sheetBodyPadding: 16
	},
	durationPreset: 'instant',
	motion: {
		hoverDuration: '120ms',
		menuDuration: '90ms',
		panelDuration: '170ms',
		sheetDuration: '210ms',
		overlayDuration: '100ms',
		toastInDuration: '280ms',
		toastOutDuration: '220ms',
		panelY: 5,
		panelScaleStart: 1
	},
	light: {
		background: '#ffffff',
		border: '#e2e3e5',
		borderStrong: '#babdc4',
		input: '#babdc4',
		primary: '#1f9be6',
		info: '#5383ed',
		foreground: '#19253e',
		muted: '#ffffff',
		panel: '#ffffff',
		foregroundMuted: '#707887',
		secondary: '#f4f4f5',
		card: '#ffffff',
		success: '#4bb673',
		warning: '#de9036',
		error: '#e14f4f',
		overlay: 'rgb(25 37 62 / 0.18)',
		ring: 'rgb(37 99 235 / 0.2)'
	},
	dark: {
		background: '#121212',
		border: '#404040',
		borderStrong: '#6c6d6e',
		input: '#6c6d6e',
		primary: '#3aaef0',
		info: '#5082c0',
		foreground: '#f0f4f9',
		muted: '#161616',
		panel: '#2c2c2d',
		foregroundMuted: '#a9acaf',
		secondary: '#27272a',
		card: '#232324',
		success: '#40a766',
		warning: '#c09426',
		error: '#bd5c5d',
		overlay: 'rgb(0 0 0 / 0.62)',
		ring: 'rgb(68 122 238 / 0.2)'
	},
	typography: {
		weightHeader: 500,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.01,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 20,
		sizeBody: 16,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	},
	pointerCursor: false
};
