import type { ThemeDraft } from '@silk/ui/themes/presets';

/**
 * Default theme -- a clean, neutral, blue-accented system: hairline gray
 * borders, soft layered shadows, an 8px radius scale, and Inter. Original
 * token values tuned for a calm, modern product UI.
 */
export const preset: ThemeDraft = {
	slug: 'default',
	name: 'Default',
	description: 'Clean neutral grays, a confident blue accent, soft elevation, and Inter.',
	publisher: 'Silk UI',
	fontSans: '"Inter", sans-serif',
	fontMono: '"Geist Mono", monospace',
	fontHeader: '"Inter", sans-serif',
	radiusBase: '0.5rem',
	radiusSm: '0.26rem',
	radiusMd: '0.5rem',
	radiusLg: '0.6rem',
	radiusXl: '0.72rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: true,
	fancyBadges: true,
	fancyShadows: true,
	hapticPress: false,
	overlaysOnSurface: true,
	pointerCursor: true,
	spacing: {
		buttonPaddingX: 15,
		badgePaddingX: 9,
		badgePaddingY: 3,
		cardPadding: 24,
		panelPadding: 8,
		fieldPaddingX: 14,
		menuItemPaddingX: 8,
		buttonHeight: 40,
		buttonHeightSm: 36,
		buttonHeightLg: 44,
		fieldHeight: 40,
		menuItemHeight: 36,
		switchTrackWidth: 40,
		switchThumbSize: 16,
		iconButtonSize: 40,
		menuPadding: 6,
		menuSearchPadding: 12,
		menuLabelPaddingX: 10,
		menuLabelPaddingY: 6,
		togglePaddingSm: 8,
		togglePaddingMd: 10,
		togglePaddingLg: 14,
		tabsTriggerPaddingX: 14,
		tabsTriggerPaddingY: 8,
		tabsListPadding: 4,
		toastPaddingX: 16,
		toastPaddingY: 16,
		calendarPadding: 12,
		colorPickerPadding: 12,
		sheetHeaderPaddingBottom: 20,
		modalPadding: 20,
		modalTitleDescriptionGap: 6,
		modalSectionGap: 20,
		sheetBodyPadding: 20,
		fieldPaddingY: 0,
		buttonGap: 8,
		switchTrackPadding: 2,
		textareaMinHeight: 120,
		textareaPaddingY: 10
	},
	animation: 'default',
	feel: 'smooth',
	light: {
		background: '#ffffff',
		border: '#e8eaee',
		borderStrong: '#d3d7df',
		input: '#d3d7df',
		primary: '#2f6bed',
		info: '#2f6bed',
		foregroundOpposite: '#ffffff',
		foreground: '#171a1f',
		muted: '#f1f2f5',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#6b7280',
		foregroundButton: '#ffffff',
		secondary: '#f5f6f8',
		card: '#ffffff',
		accent: '#f7f8fa',
		alternate: '#1c2026',
		success: '#2f9e63',
		warning: '#e09a2d',
		error: '#e2544b',
		destructive: '#d83b3b',
		overlay: 'rgb(16 18 24 / 0.42)',
		ring: 'rgb(47 107 237 / 0.2)'
	},
	dark: {
		background: '#0c0e12',
		border: '#23262e',
		borderStrong: '#30343d',
		input: '#30343d',
		primary: '#5288f5',
		info: '#6f9dff',
		foregroundOpposite: '#ffffff',
		foreground: '#eceef2',
		muted: '#15171c',
		panel: '#16191f',
		modal: '#1b1e25',
		foregroundMuted: '#969ba6',
		foregroundButton: '#ffffff',
		secondary: '#181b20',
		card: '#15171c',
		accent: '#1c2026',
		alternate: '#eceef2',
		success: '#3fb074',
		warning: '#e3a648',
		error: '#e8635b',
		destructive: '#df4747',
		overlay: 'rgb(0 0 0 / 0.6)',
		ring: 'rgb(82 136 245 / 0.3)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.017,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 18,
		sizeBody: 16,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	}
};
