import {
	defaultSpacing,
	resolveThemeMotion,
	scaleSpacing,
	type ThemeDraft
} from '@silk/ui/themes/presets';

const durationPreset = 'gentle';

export const preset: ThemeDraft = {
	slug: 'editorial',
	name: 'Editorial',
	description:
		'Warm paper, serif headlines, and a deep claret accent — a refined publication feel.',
	publisher: 'Silk UI',
	fontSans: '"Source Serif 4", serif',
	fontMono: '"IBM Plex Mono", monospace',
	fontHeader: 'Fraunces, serif',
	radiusBase: '0.4rem',
	radiusSm: '0.16rem',
	radiusMd: '0.4rem',
	radiusLg: '0.5rem',
	radiusXl: '0.62rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: true,
	fancyBadges: true,
	fancyShadows: true,
	hapticPress: false,
	spacing: scaleSpacing(defaultSpacing, 1.15),
	durationPreset,
	motion: resolveThemeMotion(durationPreset),
	light: {
		background: '#faf7f0',
		border: '#e6ddcd',
		borderStrong: '#cdbfa6',
		input: '#cdbfa6',
		primary: '#9f1239',
		info: '#3f6ad8',
		foregroundOpposite: '#ffffff',
		foreground: '#2a2018',
		muted: '#f5f0e6',
		panel: '#fffdf8',
		modal: '#fffdf8',
		foregroundMuted: '#7a6f5f',
		foregroundButton: '#ffffff',
		secondary: '#f1ebde',
		card: '#fffdf8',
		accent: '#f9ecef',
		alternate: '#3a2c20',
		success: '#4f7c3a',
		warning: '#b4791f',
		error: '#c0392b',
		destructive: '#a5311f',
		overlay: 'rgb(42 32 24 / 0.2)',
		ring: 'rgb(159 18 57 / 0.22)'
	},
	dark: {
		background: '#1a1510',
		border: '#3a3228',
		borderStrong: '#5c5142',
		input: '#5c5142',
		primary: '#ef5d86',
		info: '#6f9bf0',
		foregroundOpposite: '#0d0a07',
		foreground: '#f3ece0',
		muted: '#1f1913',
		panel: '#272018',
		modal: '#2c241b',
		foregroundMuted: '#b3a692',
		foregroundButton: '#2a0a14',
		secondary: '#2c251c',
		card: '#241d16',
		accent: '#2e1a20',
		alternate: '#ddd2c0',
		success: '#69a84f',
		warning: '#cf9a3a',
		error: '#d4685a',
		destructive: '#c2503e',
		overlay: 'rgb(0 0 0 / 0.64)',
		ring: 'rgb(239 93 134 / 0.22)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.01,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 26,
		sizeBody: 17,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	},
	overlaysOnSurface: false,
	pointerCursor: true
};
