import {
	defaultSpacing,
	resolveThemeMotion,
	scaleSpacing,
	type ThemeDraft
} from '@silk/ui/themes/presets';

const durationPreset = 'swift';

export const preset: ThemeDraft = {
	slug: 'enterprise',
	name: 'Enterprise',
	description:
		'Neutral slate surfaces and a steel-indigo accent — restrained, professional, and balanced.',
	publisher: 'Silk UI',
	fontSans: 'Manrope, sans-serif',
	fontMono: '"IBM Plex Mono", monospace',
	fontHeader: 'Manrope, sans-serif',
	radiusBase: '0.45rem',
	radiusSm: '0.21rem',
	radiusMd: '0.45rem',
	radiusLg: '0.55rem',
	radiusXl: '0.67rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: true,
	fancyBadges: true,
	fancyShadows: true,
	hapticPress: false,
	spacing: scaleSpacing(defaultSpacing, 1),
	durationPreset,
	motion: resolveThemeMotion(durationPreset),
	light: {
		background: '#ffffff',
		border: '#e5e7eb',
		borderStrong: '#cbd0d8',
		input: '#cbd0d8',
		primary: '#4f46e5',
		info: '#2563eb',
		foregroundOpposite: '#ffffff',
		foreground: '#1f2937',
		muted: '#f9fafb',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#6b7280',
		foregroundButton: '#ffffff',
		secondary: '#f3f4f6',
		card: '#ffffff',
		accent: '#eef0fb',
		alternate: '#283041',
		success: '#15803d',
		warning: '#b45309',
		error: '#dc2626',
		destructive: '#b91c1c',
		overlay: 'rgb(31 41 55 / 0.2)',
		ring: 'rgb(79 70 229 / 0.22)'
	},
	dark: {
		background: '#101216',
		border: '#2a2f37',
		borderStrong: '#434a55',
		input: '#434a55',
		primary: '#818cf8',
		info: '#60a5fa',
		foregroundOpposite: '#0a0a0a',
		foreground: '#e8eaed',
		muted: '#15171c',
		panel: '#1c1f25',
		modal: '#21242b',
		foregroundMuted: '#9aa0aa',
		foregroundButton: '#ffffff',
		secondary: '#22252c',
		card: '#181b20',
		accent: '#1e2233',
		alternate: '#cdd1d7',
		success: '#22c55e',
		warning: '#d97706',
		error: '#ef4444',
		destructive: '#dc2626',
		overlay: 'rgb(0 0 0 / 0.64)',
		ring: 'rgb(129 140 248 / 0.22)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.015,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 20,
		sizeBody: 15,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	},
	overlaysOnSurface: false,
	pointerCursor: true
};
