import {
	defaultSpacing,
	resolveThemeMotion,
	scaleSpacing,
	type ThemeDraft
} from '@silk/ui/themes/presets';

const durationPreset = 'crisp';

export const preset: ThemeDraft = {
	slug: 'financial',
	name: 'Financial',
	description: 'Institutional blue on cool slate — dense, tabular, and trustworthy.',
	publisher: 'Silk UI',
	fontSans: 'Inter, sans-serif',
	fontMono: '"IBM Plex Mono", monospace',
	fontHeader: 'Inter, sans-serif',
	radiusBase: '0.25rem',
	radiusSm: '0.14rem',
	radiusMd: '0.25rem',
	radiusLg: '0.35rem',
	radiusXl: '0.47rem',
	primaryButtonOutline: false,
	invertedPanels: false,
	fancyButtons: false,
	fancyBadges: false,
	fancyShadows: true,
	hapticPress: false,
	spacing: scaleSpacing(defaultSpacing, 0.8),
	durationPreset,
	motion: resolveThemeMotion(durationPreset),
	light: {
		background: '#ffffff',
		border: '#e2e8f0',
		borderStrong: '#cbd5e1',
		input: '#cbd5e1',
		primary: '#1d4ed8',
		info: '#2563eb',
		foregroundOpposite: '#ffffff',
		foreground: '#0f172a',
		muted: '#f8fafc',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#64748b',
		foregroundButton: '#ffffff',
		secondary: '#f1f5f9',
		card: '#ffffff',
		accent: '#eff6ff',
		alternate: '#1e293b',
		success: '#15803d',
		warning: '#b45309',
		error: '#dc2626',
		destructive: '#b91c1c',
		overlay: 'rgb(15 23 42 / 0.22)',
		ring: 'rgb(29 78 216 / 0.25)'
	},
	dark: {
		background: '#0b1120',
		border: '#1e293b',
		borderStrong: '#334155',
		input: '#334155',
		primary: '#3b82f6',
		info: '#60a5fa',
		foregroundOpposite: '#0b1120',
		foreground: '#e2e8f0',
		muted: '#0f172a',
		panel: '#111c30',
		modal: '#15233b',
		foregroundMuted: '#94a3b8',
		foregroundButton: '#ffffff',
		secondary: '#1e293b',
		card: '#0f1a2e',
		accent: '#13233f',
		alternate: '#cbd5e1',
		success: '#22c55e',
		warning: '#d97706',
		error: '#ef4444',
		destructive: '#dc2626',
		overlay: 'rgb(0 0 0 / 0.66)',
		ring: 'rgb(59 130 246 / 0.25)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.01,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 18,
		sizeBody: 14,
		sizeLabel: 13,
		sizeButton: 13,
		sizeBadge: 11
	},
	overlaysOnSurface: false,
	pointerCursor: true
};
