import {
	defaultSpacing,
	resolveThemeMotion,
	scaleSpacing,
	type ThemeDraft
} from '@silk/ui/themes/presets';

const durationPreset = 'spring';

export const preset: ThemeDraft = {
	slug: 'saas',
	name: 'SaaS Startup',
	description: 'Friendly indigo, generous spacing, and soft rounded edges — a welcoming SaaS feel.',
	publisher: 'Silk UI',
	fontSans: 'Geist, sans-serif',
	fontMono: '"Geist Mono", monospace',
	fontHeader: 'Geist, sans-serif',
	radiusBase: '0.7rem',
	radiusSm: '0.46rem',
	radiusMd: '0.7rem',
	radiusLg: '0.8rem',
	radiusXl: '0.92rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: true,
	fancyBadges: true,
	fancyShadows: true,
	hapticPress: true,
	spacing: scaleSpacing(defaultSpacing, 1.3),
	durationPreset,
	motion: resolveThemeMotion(durationPreset),
	light: {
		background: '#ffffff',
		border: '#e7e7ef',
		borderStrong: '#cdcfe0',
		input: '#cdcfe0',
		primary: '#6366f1',
		info: '#5383ed',
		foregroundOpposite: '#ffffff',
		foreground: '#1e1b2e',
		muted: '#fafafb',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#6b6b80',
		foregroundButton: '#ffffff',
		secondary: '#f4f4f8',
		card: '#ffffff',
		accent: '#eef0fe',
		alternate: '#2a2740',
		success: '#4bb673',
		warning: '#de9036',
		error: '#e14f4f',
		destructive: '#c23f3f',
		overlay: 'rgb(30 27 46 / 0.2)',
		ring: 'rgb(99 102 241 / 0.22)'
	},
	dark: {
		background: '#131318',
		border: '#33333f',
		borderStrong: '#56566a',
		input: '#56566a',
		primary: '#818cf8',
		info: '#5082c0',
		foregroundOpposite: '#09090b',
		foreground: '#f0eff7',
		muted: '#171720',
		panel: '#1f1f2b',
		modal: '#24242f',
		foregroundMuted: '#a5a5b8',
		foregroundButton: '#1a1730',
		secondary: '#272732',
		card: '#1d1d27',
		accent: '#20203a',
		alternate: '#d4d2e0',
		success: '#40a766',
		warning: '#c09426',
		error: '#bd5c5d',
		destructive: '#bf3d3e',
		overlay: 'rgb(0 0 0 / 0.62)',
		ring: 'rgb(129 140 248 / 0.22)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.02,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 22,
		sizeBody: 16,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	},
	overlaysOnSurface: false,
	pointerCursor: true
};
