import {
	defaultSpacing,
	resolveThemeMotion,
	scaleSpacing,
	type ThemeDraft
} from '@silk/ui/themes/presets';

const durationPreset = 'instant';

export const preset: ThemeDraft = {
	slug: 'terminal',
	name: 'Terminal',
	description:
		'Monospace, near-zero radius, and an acid-green accent — a precise, technical dev-tool feel.',
	publisher: 'Silk UI',
	fontSans: '"IBM Plex Mono", monospace',
	fontMono: '"Geist Mono", monospace',
	fontHeader: '"IBM Plex Mono", monospace',
	radiusBase: '0.125rem',
	radiusSm: '0.14rem',
	radiusMd: '0.125rem',
	radiusLg: '0.225rem',
	radiusXl: '0.345rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: false,
	fancyBadges: false,
	fancyShadows: false,
	hapticPress: false,
	spacing: scaleSpacing(defaultSpacing, 0.8),
	durationPreset,
	motion: resolveThemeMotion(durationPreset),
	light: {
		background: '#fafafa',
		border: '#e4e4e7',
		borderStrong: '#a1a1aa',
		input: '#a1a1aa',
		primary: '#4d7c0f',
		info: '#2563eb',
		foregroundOpposite: '#ffffff',
		foreground: '#0a0a0a',
		muted: '#f4f4f5',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#52525b',
		foregroundButton: '#ffffff',
		secondary: '#f4f4f5',
		card: '#ffffff',
		accent: '#ecfccb',
		alternate: '#18181b',
		success: '#15803d',
		warning: '#a16207',
		error: '#dc2626',
		destructive: '#b91c1c',
		overlay: 'rgb(10 10 10 / 0.2)',
		ring: 'rgb(77 124 15 / 0.3)'
	},
	dark: {
		background: '#0a0a0a',
		border: '#262626',
		borderStrong: '#404040',
		input: '#404040',
		primary: '#84cc16',
		info: '#60a5fa',
		foregroundOpposite: '#0a0a0a',
		foreground: '#e5e5e5',
		muted: '#0f0f0f',
		panel: '#161616',
		modal: '#1a1a1a',
		foregroundMuted: '#a3a3a3',
		foregroundButton: '#0a0a0a',
		secondary: '#1c1c1c',
		card: '#121212',
		accent: '#1a2410',
		alternate: '#e5e5e5',
		success: '#22c55e',
		warning: '#eab308',
		error: '#ef4444',
		destructive: '#dc2626',
		overlay: 'rgb(0 0 0 / 0.72)',
		ring: 'rgb(132 204 22 / 0.3)'
	},
	typography: {
		weightHeader: 600,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: 0,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 18,
		sizeBody: 14,
		sizeLabel: 13,
		sizeButton: 13,
		sizeBadge: 11
	},
	overlaysOnSurface: false,
	pointerCursor: true
};
