import type { ComponentSlug } from './component-anatomy';

export const componentSummaries = {
    accordion: 'Stacked sections that open one or many at a time.',
    alert: 'Inline callouts for info, success, warnings, and errors.',
    'alert-dialog': 'Confirms a consequential action before it runs.',
    attachment: 'Picks, drops, and pastes files with upload states.',
    avatar: 'A profile image that falls back to initials.',
    badge: 'Small tags for status and metadata.',
    breadcrumb: 'Shows where a page sits in a hierarchy.',
    button: 'Actions with loading, success, and error states.',
    card: 'A surface that groups related content.',
    checkbox: 'A labeled on or off choice.',
    'code-block': 'Highlighted code with language tabs and copy.',
    collapsible: 'One panel that opens and closes.',
    'color-picker': 'Picks a hex color, with optional presets.',
    combobox: 'A select you can type into and search.',
    command: 'A searchable command palette.',
    composer: 'The prompt input for a chat, with submit and stop.',
    'context-menu': 'Actions for whatever was right-clicked.',
    conversation: 'A chat viewport that follows new messages.',
    'copy-button': 'Copies text and confirms it in place.',
    'dropdown-menu': 'A menu of actions anchored to a button.',
    'file-diff': 'A unified diff with gutters and change counts.',
    'fullscreen-nav': 'A mobile menu that fills the screen.',
    gauge: 'An arc meter for usage and limits.',
    'hover-card': 'A preview that opens on hover or focus.',
    input: 'Single-line text entry with labels and adornments.',
    label: 'A styled native label for a form control.',
    markdown: 'Renders model Markdown with raw HTML shown as text.',
    message: 'One chat turn, aligned by role, with actions.',
    modal: 'A centered dialog for forms and confirmations.',
    'navigation-menu': 'A site header menu whose panels share one morphing viewport.',
    pagination: 'Moves between pages of a long list.',
    popover: 'A floating panel anchored to a trigger.',
    progress: 'How far along a task is, or that it is running.',
    question: 'Asks the user a choice or free-text question inline.',
    'radio-group': 'Picks exactly one option from a short list.',
    reasoning: 'A collapsible trace of the model’s thinking.',
    'reorder-list': 'Reorders items by dragging or with the keyboard.',
    'response-stream': 'Reveals streamed text at a steady pace.',
    'scroll-area': 'A scroll container with a themed scrollbar.',
    select: 'Picks one option from a known list.',
    sheet: 'A panel that slides in from the left or right edge.',
    shortcut: 'Shows a keyboard shortcut and runs it on keypress.',
    'show-more': 'Clamps long content until it is expanded.',
    sidebar: 'A collapsible app-shell navigation column with an inset layout.',
    skeleton: 'Placeholders that hold layout while loading.',
    slider: 'Scrubs a number with its label inside the field.',
    spinner: 'Signals indeterminate work.',
    switch: 'Turns a setting on or off immediately.',
    tabs: 'Switches between views with a sliding indicator.',
    'tag-input': 'Enters a list of tags with keyboard and paste.',
    'task-steps': 'Shows progress through an ordered list of steps.',
    textarea: 'Multi-line text entry.',
    toast: 'Brief notifications fired from anywhere.',
    toggle: 'A button that stays pressed or unpressed.',
    'toggle-group': 'A row of toggles with shared selection.',
    tool: 'Collapsible groups of an assistant’s tool calls.',
    tooltip: 'Brief help text on hover or focus.',
    typography: 'Headings, body text, inline code, and metadata.'
} satisfies Record<ComponentSlug, string>;
